### ISSUE TITLE
Incorrect path 

### ISSUE THREAD

**Issue by stagfoo** [Akira-Wang/animalfunfacts#3]
https://github.com/Akira-Wang/animalfunfacts/blob/3fda1a0db1a49176d63d9d660253bd05e993fd10/index.html#L10

https://akira-wang.github.io/animalfunfacts/
The final domain is /animalfunfacts/ so 

This line is look at https://akira-wang.github.io/app.compiled.js not https://akira-wang.github.io/animalfunfacts/app.compiled.js

**Comment by stagfoo** [comment]
https://youtu.be/ephId3mYu9o

**Comment by Akira-Wang** [comment]
Thanks, let me try

**Comment by Akira-Wang** [comment]
I changed to this
	<script src="app.compiled.js"></script>

**Comment by Akira-Wang** [comment]
the JSX code works now

**Comment by Akira-Wang** [comment]
I guess I have to change other JPG image link to relative path too now

**Comment by stagfoo** [comment]
👍 yep

**Comment by stagfoo** [comment]
Or change everything /animalfunfacts/app.compiled.js and update your local service to run one folder higher
